version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: curseduca_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: curseduca
      MYSQL_DATABASE: curseduca
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE